### ISSUE TITLE
请问当内容为从1000到2000，怎么整体向上滚动，而不是只有1向上滚动成2

### ISSUE THREAD

**Issue by njzhangsan2013** [YvesCheung/RollingText#1]

**Comment by YvesCheung** [comment]
final CharOrderStrategy strategy = new NormalAnimationStrategy() {
            @NotNull
            @Override
            public Pair<List<Character>, Direction> findCharOrder(
                    char sourceChar,
                    char targetChar,
                    int index,
                    @Nullable Iterable<Character> order) {

                if (sourceChar == targetChar) {
                    return new Pair<>(Arrays.asList(sourceChar, targetChar), Direction.SCROLL_DOWN);
                } else {
                    return super.findCharOrder(sourceChar, targetChar, index, order);
                }
            }
        };
        final RollingTextView rollingTextView = findViewById(R.id.text_id);
        rollingTextView.addCharOrder(CharOrder.Number);
        rollingTextView.setCharStrategy(strategy);
        rollingTextView.setText("1000", false);
        rollingTextView.setText("2000");

请问是这种效果吗？

**Comment by njzhangsan2013** [comment]
谢谢，大概对了，就是方向和我的相反，还有如果我这个数字中有中文，怎么不让它一起滚动

**Comment by YvesCheung** [comment]
//用SameDirectionStrategy装饰一次 指定自己需要的方向
        final CharOrderStrategy strategy = new SameDirectionStrategy(
                Direction.SCROLL_UP, //最后要向上滚还是向下滚在这里指定
                new NormalAnimationStrategy() {
                    @NotNull
                    @Override
                    public Pair<List<Character>, Direction> findCharOrder(
                            char sourceChar,
                            char targetChar,
                            int index,
                            @Nullable Iterable<Character> order) {

                        //相同且是数字
                        if (sourceChar == targetChar && Character.isDigit(sourceChar)) {
                            return new Pair<>(Arrays.asList(sourceChar, targetChar), Direction.SCROLL_DOWN);
                        } else {
                            return super.findCharOrder(sourceChar, targetChar, index, order);
                        }
                    }
                });
        final RollingTextView rollingTextView = findViewById(R.id.carryTextView);
        rollingTextView.addCharOrder(CharOrder.Number);
        rollingTextView.setCharStrategy(strategy);
        rollingTextView.setText("中文：1000", false);
        rollingTextView.setText("中文：2000");

**Comment by njzhangsan2013** [comment]
非常感谢，完美解决了我的问题
