### ISSUE TITLE
1.2.2 version - compilation error

### ISSUE THREAD

**Issue by Bendor** [YvesCheung/RollingText#10]
Hello! First of all thanks  for this good project!
I have a little problem with last update 1.2.2:  _Unresolved reference: RollingTextView_ 
I can't found this class at all. On 1.2.1 version everything is ok.
Please take a look. Thanks!

**Comment by YvesCheung** [comment]
Thank you very much for your reminder. 
This problem is due to the publication of the wrong classes .jar and it has been fixed in 1.2.3.
