### ISSUE TITLE
Unable to install dependency

### ISSUE THREAD

**Issue by nileshtupe31** [YvesCheung/RollingText#12]
I have a java android project.
I followed 2 steps given to install RollingText in my project.
After that Gradle syncs successfully without any error but when I try to access 
<com.yy.mobile.rollingtextview.RollingTextView in xml or RollingTextView in Java class file, it could not find the class.

**Comment by YvesCheung** [comment]
The same as #10 .
Thank you very much for your reminder and this problem has been fixed in 1.2.3.

**Comment by nileshtupe31** [comment]
Thank you so much!!!
