### ISSUE TITLE
长度不同的两个字符串切换，短的被右对齐了 是怎么回事

### ISSUE THREAD

**Issue by aa86799** [YvesCheung/RollingText#13]
RT

**Comment by YvesCheung** [comment]
因为大部分数学计算都是右对齐的。
添加左对齐策略，代码提交： 744f9127de9ae6a2f73bff2a1c5fe26a86e1dac5
v1.2.4带上 AlignAnimationStrategy

**Comment by aa86799** [comment]
thx.
