### ISSUE TITLE
如何设置字体左对齐，现在滚动会左右滑动

### ISSUE THREAD

**Issue by 1181631922** [YvesCheung/RollingText#14]

**Comment by YvesCheung** [comment]
setCharStrategy(new AlignAnimationStrategy(TextAlignment.Left));
看看能不能满足你需求

**Comment by 1181631922** [comment]
不行，你试一下字数不一样的情况

**Comment by YvesCheung** [comment]
文本外层的布局是怎样的？

**Comment by 1181631922** [comment]
<RelativeLayout
            android:id="@+id/manyFragmentTitle"
            android:layout_width="match_parent"
            android:background="#1c1c1c"
            android:layout_height="40dp">

        <ImageView
                android:id="@+id/ivFragmentIcon"
                android:layout_width="33dp"
                android:padding="9dp"
                android:layout_height="match_parent"
                android:src="@drawable/go_back_left_arrow"/>

        <com.meili.moon.imagepicker.view.rollingtextview.RollingTextView
                android:id="@+id/tvFragmentTitle"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:text=""
                android:textSize="15dp"
                android:layout_toRightOf="@+id/ivFragmentIcon"
                android:textColor="#a09fa3"
                android:gravity="center_vertical"/>


        <LinearLayout
                android:id="@+id/layoutPhotoAlbum"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:paddingLeft="30dp"
                android:paddingRight="30dp"
                android:layout_centerHorizontal="true"
                android:orientation="horizontal">
            <TextView
                    android:id="@+id/photoAlbum"
                    android:layout_width="wrap_content"
                    android:layout_height="match_parent"
                    android:text="所有图片"
                    android:textSize="15dp"
                    android:textColor="#a09fa3"
                    android:gravity="center_vertical"/>

            <ImageView
                    android:id="@+id/photoAlbumArrow"
                    android:layout_width="10dp"
                    android:layout_height="5dp"
                    android:src="@drawable/mn_to_bottom_arrow"
                    android:rotation="180"
                    android:layout_gravity="center_vertical"/>
        </LinearLayout>
        <TextView
                android:id="@+id/layoutPhotoConfirm"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:text="确定"
                android:paddingLeft="20dp"
                android:paddingRight="20dp"
                android:gravity="center_vertical"
                android:layout_alignParentRight="true"
                android:textSize="16dp"
                android:textColor="@android:color/white"/>

    </RelativeLayout>

**Comment by 1181631922** [comment]
数字不一样也不行，字数不一样就不行，一样的话数字和文字都可以

**Comment by YvesCheung** [comment]
99af56df16634ec329f682d9d88affa168ea2b8c
我按照你的布局写demo，是有左对齐的。

你跑一下这个demo看看有什么区别？或者提供一下你变化前后的字符串
