### ISSUE TITLE
相同的文本内容setTextView是没有办法滚动吗？

### ISSUE THREAD

**Issue by wuyubo0522** [YvesCheung/RollingText#16]
开发当中，我遇到相同的文本内容出现无法滚动情况，请问有解决办法吗？

**Comment by YvesCheung** [comment]
无法滚动是故意而为之。
可以重写滚动策略来描述你想要的滚动效果

**Comment by YvesCheung** [comment]
参考这个类 [NormalAnimationStrategy](https://github.com/YvesCheung/RollingText/blob/master/rollingtextview/src/main/java/com/yy/mobile/rollingtextview/strategy/NormalAnimationStrategy.kt)

```
 if (sourceChar == targetChar) {
    return listOf(targetChar) to Direction.SCROLL_DOWN
 }
```

改为

```
 if (sourceChar == targetChar) {
    return listOf(sourceChar,targetChar) to Direction.SCROLL_DOWN
 }
```
则字符相同时，也会出现 `sourceChar` 到 `targetChar` 的向下滚动
