### ISSUE TITLE
RollingText Font 

### ISSUE THREAD

**Issue by arvindy10** [YvesCheung/RollingText#17]
Hi , 
How I can use another text font family?

**Comment by YvesCheung** [comment]
RollingTextView#typeface

**Comment by deneme721a** [comment]
@YvesCheung  setTypeFace creates distortion in the view. I think includeFontPadding, the default padding, is causing inflation. Maybe it could be related to lineSpacing, I don't know. Please check RollingText by setting drawable background in XML. as before and after
``
binding.weightTextView.setTypeface(ResourcesCompat.getFont(this, R.font.poppins_bold));
``
