### ISSUE TITLE
请教一下能否实现左右滑动

### ISSUE THREAD

**Issue by coolyunyun** [YvesCheung/RollingText#20]
![image](https://user-images.githubusercontent.com/24830302/77602353-38d47e80-6f48-11ea-9831-f339b58d0281.png)
正中间这样左右滑动的效果这个能实现么，或者如何实现

**Comment by YvesCheung** [comment]
这个不是png吗..怎么滑动

**Comment by coolyunyun** [comment]
[http://chuantu.xyz/t6/726/1585196880x2890149815.gif](url)
这个gif图的 正中间左右滚动的效果 能实现么?

**Comment by coolyunyun** [comment]
http://chuantu.xyz/t6/726/1585196880x2890149815.gif

**Comment by coolyunyun** [comment]
http://chuantu.xyz/t6/726/1585196880x2890149815.gif

这个gif图的 正中间左右滚动的效果 能实现么?

**Comment by YvesCheung** [comment]
可以实现 我看看怎么暴露给外面设置

**Comment by coolyunyun** [comment]
万分感谢，宇哥霸气！

**Comment by YvesCheung** [comment]
水平方向滚动的代码： 5a328131c657d44795dae1d152c5dda8732e88b1 
release 1.2.6

`Direction` 添加了 `SCROLL_LEFT` `SCROLL_RIGHT` 两种枚举
`MainActivity` 添加了同时往四个方向滚动的demo
