### ISSUE TITLE
父布局属性动画上下移动，rollingtextview会有明显的抖动

### ISSUE THREAD

**Issue by dongxingrong** [YvesCheung/RollingText#22]
父布局添加上下移动的属性动画，对比普通的textview，rollingtextview会明显上下抖动；
demo关键代码：
                tvButton.setText("1000", true);

                Keyframe k0 = Keyframe.ofFloat(0.0f, 0.0f);
                Keyframe k1 = Keyframe.ofFloat(0.5f, 10.0f);
                Keyframe k2 = Keyframe.ofFloat(1.0f, 0.0f);
                PropertyValuesHolder translationY = PropertyValuesHolder.ofKeyframe("translationY", k0, k1, k2);

                mTranslationYAnimator = ObjectAnimator.ofPropertyValuesHolder(container, translationY);
                mTranslationYAnimator.setInterpolator(new LinearInterpolator());
                mTranslationYAnimator.setRepeatCount(ValueAnimator.INFINITE);
                mTranslationYAnimator.setDuration(3500);
                mTranslationYAnimator.start();

**Comment by dongxingrong** [comment]
debug定位到是canvas.translate方法导致抖动；

**Comment by YvesCheung** [comment]
加了demo的代码[Issue22Activity.java](https://github.com/YvesCheung/RollingText/blob/master/app/src/main/java/com/yy/mobile/rollingtext/Issue22Activity.java)，但看上去没有明显的抖动
