### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by whoislxy** [YvesCheung/RollingText#29]
java.util.ConcurrentModificationException
com.yy.mobile.rollingtextview.RollingTextView.onDraw(RollingTextView.kt:23)

**Comment by YvesCheung** [comment]
Require a full stacktrace

**Comment by YvesCheung** [comment]
![image](https://user-images.githubusercontent.com/18024705/113259391-a6577f80-92ff-11eb-8c52-3d32e70135a3.png)
Line 23 in RollingTextView.kt is a import statement...
