### ISSUE TITLE
Error:(17, 27) Dimension types not allowed (at 'shadowDy' with value '4dp').

### ISSUE THREAD

**Issue by CPT-CJS** [YvesCheung/RollingText#3]
<com.yy.mobile.rollingtextview.RollingTextView
        android:id="@+id/alphaBetView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:shadowColor="#ffdd00"
        android:shadowDx="4dp"
        android:shadowDy="4dp"
        android:text="i am text"
        android:textColor="#1d1d1d"
        android:textSize="25sp"
        android:textStyle="bold"/>

直接按照例子跑爆这个错误
Error:(17, 27) Dimension types not allowed (at 'shadowDy' with value '4dp').

**Comment by YvesCheung** [comment]
感谢提醒。修改了例子：
<com.yy.mobile.rollingtextview.RollingTextView
    android:id="@+id/alphaBetView"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="i am text"
    android:textSize="25sp" 
    android:textColor="#1d1d1d"
    android:textStyle="bold"
    android:gravity="center"
    android:shadowColor="#ff44ffdd"
    android:shadowDx="10"
    android:shadowDy="10"
    android:shadowRadius="10"/>
