### ISSUE TITLE
请问如果要给每个字符设定背景样式怎么修改呢？

### ISSUE THREAD

**Issue by FrankyLee-dev** [YvesCheung/RollingText#30]
比如这样：
![aaaa](https://user-images.githubusercontent.com/17977044/123243422-970a5b80-d515-11eb-95b6-1990d3d15298.png)

**Comment by YvesCheung** [comment]
比较简单的是直接把这个拆成多个TextView来做，一个数字一个TextView

**Comment by YvesCheung** [comment]
第二种方法是重写TextManager的draw方法
![image](https://user-images.githubusercontent.com/18024705/123386837-aa76fe80-d5c9-11eb-839a-4d12d3c3119e.png)

`it.draw(canvas)` 这里是画文字，在这一句之前在canvas上先画上背景

**Comment by FrankyLee-dev** [comment]
好的，已经用第二种方法实现了。谢谢！
