### ISSUE TITLE
更换字体后字符显示不全

### ISSUE THREAD

**Issue by szyyycs** [YvesCheung/RollingText#36]
更换字体后每个字符显示宽度都不足，导致每个英文字符都显示不全

**Comment by szyyycs** [comment]
以及letterSpacingExtra这个属性和原来的letterspacing对应关系是什么呢

**Comment by YvesCheung** [comment]
是通过typeface设置的字体吗？字体文件方便给一下吗

**Comment by YvesCheung** [comment]
@szyyycs letterSpacingExtra是想模拟letterspacing的效果，但实现不一样

**Comment by szyyycs** [comment]
> 是通过typeface设置的字体吗？字体文件方便给一下吗

我怎么提供给你呢，还有所以就是letterSpacingExtra目前和letterspacing没有具体的对应关系是吧？

**Comment by szyyycs** [comment]
我用的字体是@font/riviera_nights_light，通过this.typeface = ResourcesCompat.getFont(context, font)在继承的子类里的init里设置的

**Comment by YvesCheung** [comment]
10effcc0693262b7f8356fd6d9f034bb4bb139fd
我没有你的字体文件，只能另外下了一个去试，但没能复现。
要不你就用letterSpacingExtra拉大一下间距看能不能解决

**Comment by szyyycs** [comment]
> [10effcc](https://github.com/YvesCheung/RollingText/commit/10effcc0693262b7f8356fd6d9f034bb4bb139fd) 我没有你的字体文件，只能另外下了一个去试，但没能复现。 要不你就用letterSpacingExtra拉大一下间距看能不能解决


[riviera.otf.zip](https://github.com/YvesCheung/RollingText/files/12518556/riviera.otf.zip)
这是我的字体文件，我试过拉大间距，但是不行，字体小的时候好像显示问题不大，大到30以上就不行了

**Comment by YvesCheung** [comment]
嗯这个复现了，当中间的字符比如w比最终的字符宽度要长，就会被截断。我看看怎么修

**Comment by YvesCheung** [comment]
@szyyycs 看看1.3.0符不符合预期

**Comment by szyyycs** [comment]
好了，十分感谢大佬～
