### ISSUE TITLE
数字的边角有些粗糙

### ISSUE THREAD

**Issue by noiary** [YvesCheung/RollingText#6]
数字在用力注释下，边边上会有些粗糙，看起来很像是没开抗锯齿的感觉。
然而我追了下源码，又看到开了抗锯齿，作者知道是什么原因吗？

**Comment by 401885064** [comment]
同样的问题    数字看起来粗糙了   看onDraw方法没开锯齿    希望作者能修改下

**Comment by 401885064** [comment]
升级到1.2.1版本  解决此问题

**Comment by ARC-XX** [comment]
不好意思各位，我是一名新手，请为文中的"在对应的module 中添加依赖"具体怎样操作，应该把代码放到哪里？

**Comment by hellosuperX** [comment]
> 不好意思各位，我是一名新手，请为文中的"在对应的module 中添加依赖"具体怎样操作，应该把代码放到哪里？

哈哈哈哈哈。这个回复好可爱

**Comment by tianshaokai** [comment]
要是有java版本就好了

**Comment by YvesCheung** [comment]
与该Issue“数字的边角有些粗糙 ”无关的问题可以另外新建一个Issue，方便问题归类与跟进。
