### ISSUE TITLE
开发java版本吗

### ISSUE THREAD

**Issue by tianshaokai** [YvesCheung/RollingText#9]
要是有java版本就好了，对于不懂kotlin的开发者只能望尘莫及了

_Originally posted by @tianshaokai in https://github.com/YvesCheung/RollingText/issues/6#issuecomment-450832429_

**Comment by YvesCheung** [comment]
在Android领域的话，Java是迟早会被Kotlin取代的。早点学习Kotlin，取代的是语言，否则取代的是开发者。
